/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scenes/Main.ls
 */
export class mainBase extends Laya.Scene {
    public bird!: Laya.Sprite;
}

